### ISSUE TITLE
Rule 17 "Competitors may start their robots" need a final decision

### ISSUE THREAD

**Issue by Dasepho** [sourcebots/smallpeice-rules#13]
We need to choose:
- Competitors can start their robots
- We (volunteers) will start them

**Comment by trickeydan** [comment]
This is dependent on schedule.

**Comment by tpoomlmly** [comment]
I think that competitors should at least be allowed to put their robots in the arena themselves, but if we also let them start the robots themselves then we'll have to think of some rules for false starts.

**Comment by RealOrangeOne** [comment]
For the last couple years we've had it that competitors aren't allowed "arena side" at all during matches, mostly because we're better trained at doing things around the arena, and having smallpeice competitors faffing around the arena between matches means we need a much larger padding between matches, resulting in fewer matches.

What's the thinking around changing this?

Paging @prophile for additional context.

**Comment by tpoomlmly** [comment]
The final decision was that competitors could put their robots in the arena, but volunteers would start them.
